# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog10_tianjiarenwu.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(471, 354)
        Dialog.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 6, QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 9, 4, 1, 1, QtCore.Qt.AlignRight)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 8, 4, 1, 1, QtCore.Qt.AlignRight)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_6.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_6.setSizePolicy(sizePolicy)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.gridLayout.addWidget(self.doubleSpinBox_6, 10, 5, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_2.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_2.setSizePolicy(sizePolicy)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout.addWidget(self.doubleSpinBox_2, 8, 5, 1, 1)
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 10, 4, 1, 1, QtCore.Qt.AlignRight)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_4.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_4.setSizePolicy(sizePolicy)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout.addWidget(self.doubleSpinBox_4, 9, 5, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 8, 0, 3, 1)
        self.label_13 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 11, 0, 1, 1)
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(Dialog)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.gridLayout.addWidget(self.dateTimeEdit_2, 7, 4, 1, 2)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(Dialog)
        self.dateTimeEdit.setCalendarPopup(False)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout.addWidget(self.dateTimeEdit, 7, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 7, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 15, 4, 1, 1)
        self.label_14 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 12, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 15, 5, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 7, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_10 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_10.setObjectName("radioButton_10")
        self.horizontalLayout_2.addWidget(self.radioButton_10)
        self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_11.setObjectName("radioButton_11")
        self.horizontalLayout_2.addWidget(self.radioButton_11)
        self.radioButton_12 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_12.setChecked(True)
        self.radioButton_12.setObjectName("radioButton_12")
        self.horizontalLayout_2.addWidget(self.radioButton_12)
        self.radioButton_13 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_13.setObjectName("radioButton_13")
        self.horizontalLayout_2.addWidget(self.radioButton_13)
        self.radioButton_14 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_14.setObjectName("radioButton_14")
        self.horizontalLayout_2.addWidget(self.radioButton_14)
        self.gridLayout.addWidget(self.groupBox, 6, 1, 1, 5)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_5.setChecked(True)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout_3.addWidget(self.radioButton_5)
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_7.setObjectName("radioButton_7")
        self.horizontalLayout_3.addWidget(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_8.setObjectName("radioButton_8")
        self.horizontalLayout_3.addWidget(self.radioButton_8)
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_9.setObjectName("radioButton_9")
        self.horizontalLayout_3.addWidget(self.radioButton_9)
        self.gridLayout.addWidget(self.groupBox_3, 4, 1, 1, 5)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.radioButton_15 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_15.setObjectName("radioButton_15")
        self.horizontalLayout.addWidget(self.radioButton_15)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout.addWidget(self.radioButton_4)
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout.addWidget(self.radioButton_6)
        self.gridLayout.addWidget(self.groupBox_2, 2, 1, 1, 5)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 11, 1, 1, 5)
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 12, 1, 1, 5)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 9, 1, 1, 1, QtCore.Qt.AlignRight)
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 10, 1, 1, 1, QtCore.Qt.AlignRight)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 8, 1, 1, 1, QtCore.Qt.AlignRight)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox.setSizePolicy(sizePolicy)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 8, 2, 1, 1)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_3.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_3.setSizePolicy(sizePolicy)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.gridLayout.addWidget(self.doubleSpinBox_3, 9, 2, 1, 1)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_5.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_5.setSizePolicy(sizePolicy)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.gridLayout.addWidget(self.doubleSpinBox_5, 10, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 15, 0, 1, 1)
        self.pushButton_3.setText('换行')
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)


        #### 按键的基本条件控制，包括加点限定，时间设定，过程任务开关等
        self.doubleSpinBox.setSingleStep(0.001)
        self.doubleSpinBox.setDecimals(3)
        self.doubleSpinBox.setMinimum(-1)
        self.doubleSpinBox.setMaximum(1)
        self.doubleSpinBox_2.setSingleStep(0.001)
        self.doubleSpinBox_2.setDecimals(3)
        self.doubleSpinBox_2.setMinimum(-1)
        self.doubleSpinBox_2.setMaximum(1)
        self.doubleSpinBox_3.setSingleStep(0.001)
        self.doubleSpinBox_3.setDecimals(3)
        self.doubleSpinBox_3.setMinimum(-1)
        self.doubleSpinBox_3.setMaximum(1)
        self.doubleSpinBox_4.setSingleStep(0.001)
        self.doubleSpinBox_4.setDecimals(3)
        self.doubleSpinBox_4.setMinimum(-1)
        self.doubleSpinBox_4.setMaximum(1)
        self.doubleSpinBox_5.setSingleStep(0.001)
        self.doubleSpinBox_5.setDecimals(3)
        self.doubleSpinBox_5.setMinimum(-1)
        self.doubleSpinBox_5.setMaximum(1)
        self.doubleSpinBox_6.setSingleStep(0.001)
        self.doubleSpinBox_6.setDecimals(3)
        self.doubleSpinBox_6.setMinimum(-1)
        self.doubleSpinBox_6.setMaximum(1)
        global guochengrenwu
        guochengrenwu = 0
        import datetime
        nian = datetime.date.today().year
        yue = datetime.date.today().month
        ri = datetime.date.today().day
        xiaoshi = datetime.datetime.today().hour
        jintian = datetime.date.today()
        ji = datetime.date.today().weekday()
        xingqi = ['星期一','星期二','星期三','星期四','星期五','星期六','星期天']
        self.dateTimeEdit_2.setEnabled(True)
        self.dateTimeEdit.setEnabled(False)

        def shijianfanwei():
            global guochengrenwu
            if guochengrenwu == 0:
                self.dateTimeEdit.setEnabled(True)
                self.label_15.setEnabled(True)
                guochengrenwu = 1
                return
            if guochengrenwu == 1:
                self.dateTimeEdit.setEnabled(False)
                self.label_15.setEnabled(False)
                guochengrenwu = 0
                return
        self.label.setText('今天是：'+str(jintian)+'  '+xingqi[ji])
        self.dateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(nian,yue,ri), QtCore.QTime(xiaoshi, 0, 0)))
        self.dateTimeEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(nian,yue,ri), QtCore.QTime(xiaoshi, 0, 0)))
        self.checkBox.clicked.connect(shijianfanwei)

        #### 生成一个标识符，放在末尾，在后面显示任务的时候，可以用此来匹配显示哪个变量的弹窗
        def GenID():
            import string
            from random import choice
            length=8
            chars=string.ascii_letters+string.digits
            return ''.join([choice(chars) for i in range(length)])


        def queding():
            add = []
            time = self.dateTimeEdit_2.date().year()*365+self.dateTimeEdit_2.date().month()*30+self.dateTimeEdit_2.date().day()
            ###前三个变量，第一个是用于比较时间排序，第二个是任务开始时间（可为空），第三个是任务结束时间也就是用于排序的时间（后面过期任务将受到经验和娱乐点减半的惩罚）
            if self.checkBox.isChecked():
                add.append(time)
                add.append(self.dateTimeEdit.text())
                add.append(self.dateTimeEdit_2.text())
            else:
                add.append(time)
                add.append('')
                add.append(self.dateTimeEdit_2.text())

            ### 第四个变量获得分类，第五个变量获得重要性
            if self.radioButton.isChecked():
                add.append(1)
            elif self.radioButton_2.isChecked():
                add.append(2)
            elif self.radioButton_15.isChecked():
                add.append(3)
            elif self.radioButton_3.isChecked():
                add.append(4)
            elif self.radioButton_4.isChecked():
                add.append(5)
            elif self.radioButton_6.isChecked():
                add.append(6)

            if self.radioButton_5.isChecked():
                add.append(1)
            elif self.radioButton_7.isChecked():
                add.append(2)
            elif self.radioButton_8.isChecked():
                add.append(3)
            elif self.radioButton_9.isChecked():
                add.append(4)

            ### 第六个变量获得名称，第七个变量获得描述，第八个到第十三个变量获得基本属性点
            add.append(self.lineEdit.text())
            add.append(self.lineEdit_2.text())
            add.append(float(self.doubleSpinBox.text()))
            add.append(float(self.doubleSpinBox_3.text()))
            add.append(float(self.doubleSpinBox_5.text()))
            add.append(float(self.doubleSpinBox_2.text()))
            add.append(float(self.doubleSpinBox_4.text()))
            add.append(float(self.doubleSpinBox_6.text()))

            ### 第十四个变量获得经验，第十五个变量获得娱乐点
            if self.radioButton_10.isChecked():
                add.append(14)
                add.append(4)
            if self.radioButton_11.isChecked():
                add.append(11)
                add.append(3)
            if self.radioButton_12.isChecked():
                add.append(8)
                add.append(2)
            if self.radioButton_13.isChecked():
                add.append(5)
                add.append(1)
            if self.radioButton_14.isChecked():
                add.append(0)
                add.append(0)

            ### 第十六个变量添加一个ID，用于显示浮动窗口的时候识别
            add.append(GenID())

            ###储存这个变量到每日任务变量
            import pickle
            path = open('D:/MyRPG/data.dat','rb')
            global dianshu,nengli,zhuangbei,xiguangeverday,xiguanall,renwu,renwufinish,rizhi,rizhifinish,jiangli,jiangliget,yuanwang
            dianshu,nengli,zhuangbei,xiguangeverday,xiguanall,renwu,renwufinish,rizhi,rizhifinish,jiangli,jiangliget,yuanwang = pickle.load(path)
            path.close()
            del path
            renwu.append(add)
            # print(renwu)
            path = open('D:/MyRPG/data.dat','wb')
            pickle.dump((dianshu,nengli,zhuangbei,xiguangeverday,xiguanall,renwu,renwufinish,rizhi,rizhifinish,jiangli,jiangliget,yuanwang),path)
            path.close()
            del path
            # print(len(renwu))
            Dialog.destroy()
        def tuichu():
            Dialog.destroy()
        def huanhang():
            self.lineEdit_2.insert('<br/>')
        self.pushButton.clicked.connect(queding)
        self.pushButton_2.clicked.connect(tuichu)
        self.pushButton_3.clicked.connect(huanhang)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "添加任务"))
        self.label_2.setText(_translate("Dialog", "分类"))
        self.label_4.setText(_translate("Dialog", "难度"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#0000ff;\">今天的日期和星期几</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "重要性"))
        self.label_10.setText(_translate("Dialog", "智力："))
        self.label_8.setText(_translate("Dialog", "专注："))
        self.label_12.setText(_translate("Dialog", "知识量："))
        self.label_6.setText(_translate("Dialog", "设定点数加成/减益"))
        self.label_13.setText(_translate("Dialog", "名称"))
        self.label_15.setText(_translate("Dialog", "至"))
        self.label_5.setText(_translate("Dialog", "时间"))
        self.pushButton.setText(_translate("Dialog", "确定"))
        self.label_14.setText(_translate("Dialog", "描述"))
        self.pushButton_2.setText(_translate("Dialog", "取消"))
        self.checkBox.setText(_translate("Dialog", "过程任务"))
        self.radioButton_10.setText(_translate("Dialog", "非常困难"))
        self.radioButton_11.setText(_translate("Dialog", "困难"))
        self.radioButton_12.setText(_translate("Dialog", "一般"))
        self.radioButton_13.setText(_translate("Dialog", "简单"))
        self.radioButton_14.setText(_translate("Dialog", "日常必须任务"))
        self.radioButton_5.setText(_translate("Dialog", "重要且紧急"))
        self.radioButton_7.setText(_translate("Dialog", "重要但不紧急"))
        self.radioButton_8.setText(_translate("Dialog", "紧急但不重要"))
        self.radioButton_9.setText(_translate("Dialog", "不重要不紧急"))
        self.radioButton.setText(_translate("Dialog", "工作"))
        self.radioButton_2.setText(_translate("Dialog", "生活"))
        self.radioButton_15.setText(_translate("Dialog", "理财"))
        self.radioButton_3.setText(_translate("Dialog", "琐事"))
        self.radioButton_4.setText(_translate("Dialog", "自我提升"))
        self.radioButton_6.setText(_translate("Dialog", "其他"))
        self.label_9.setText(_translate("Dialog", "体重："))
        self.label_11.setText(_translate("Dialog", "耐力："))
        self.label_7.setText(_translate("Dialog", "体质："))

# import sys
# app = QtWidgets.QApplication(sys.argv)
# Dialog = QtWidgets.QDialog()
# ui = Ui_Dialog()
# ui.setupUi(Dialog)
# Dialog.show()
# sys.exit(app.exec_())